services:
  - type: web
    name: fingertalk-fastapi
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -k uvicorn.workers.UvicornWorker --timeout 120 --workers 1 --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 10000
    plan: free
